### ISSUE TITLE
Make sure the program behaves properly when the = is pressed repeatedly.

### ISSUE THREAD

**Issue by jhempy** [bootcamp-f18/js-calculator#2]

**Comment by kendrajordan** [comment]
I added a case for "=" that if it is added as an operator then the calculator would clear. Now if your repeatedly press the equal sign when the display is zero, then you don't receive an alert. If you press the the equal three times after calculating an equation, then the display clears to zero.
function calculate() {

    let total = 0;

    switch (operator) {

        case "/":
            total = Number(value1) / Number(value2);
            break;
        case "X":
            total = Number(value1) * Number(value2);
            break;
        case "-":
            total = Number(value1) - Number(value2);
            break;
        case "+":
            total = Number(value1) + Number(value2);
            break;
        case"=":
            clearWasEntered();
            break;
        default:
            alert("No function selected!");
            break;

    }

    return total;

**Comment by MatthewGidcomb** [comment]
We fixed this in class today while writing tests. Now if you press = repeatedly it repeats the last calculation.
`1 + 2 = 3 = 5 = 7 ...`
